### ISSUE TITLE
Add option to run `go mod vendor` as well after `go mod tidy`

### ISSUE THREAD

**Issue by johanbrandhorst** [sue445/go-mod-tidy-pr#22]
In repos where there is a vendor directory, we'd like to be able to run `go mod vendor` as well as `go mod tidy`.

**Comment by sue445** [comment]
Which do you prefer followings?

1. run `go mod vendor` before `go mod tidy`
2. run `go mod vendor` after `go mod tidy`

**Comment by johanbrandhorst** [comment]
The latter, `go mod vendor` after `go mod tidy`.

**Comment by sue445** [comment]
@johanbrandhorst I released as `v1.3.0`

https://github.com/sue445/go-mod-tidy-pr/releases/tag/v1.3.0
