### ISSUE TITLE
Hardcoding golang version to latest causing issue for code with older versions

### ISSUE THREAD

**Issue by superliuwr** [sue445/go-mod-tidy-pr#31]
We are still using go v1.13.4 in our code and it seems to cause some issues when `go-mod-tidy-pr` is running on the latest v1.14 version.

Here is the error message:
```
go: errors parsing go.mod:
/github/workspace/go/src/ddb/go.mod:3: usage: go 1.23
```

It would be great if we can make the go version configurable. Thank you!

**Comment by sue445** [comment]
This feature was implemented in #32 and released as `v1.4.0`
