### ISSUE TITLE
timezoneパラメータが無効に思われる

### ISSUE THREAD

**Issue by tkms0106** [sue445/go-mod-tidy-pr#33]
`timezone`に`Asia/Tokyo`を指定して利用したところ、プルリクエストのタイトルが下記のようになりました。
`go mod tidy at Mon May 18 03:04:31 Asia 2020`

おそらく、Dockerイメージにzoneinfoが存在していないためではないかと思います。
https://github.com/sue445/go-mod-tidy-pr/blob/cabdcb29b136eca73ed998dae690b44822ee5562/Dockerfile#L1
![image](https://user-images.githubusercontent.com/23391543/82172590-8a283b00-9905-11ea-9e12-1c2abe0a7abe.png)

![image](https://user-images.githubusercontent.com/23391543/82172654-c360ab00-9905-11ea-833b-00e365664227.png)

**Comment by sue445** [comment]
@tkms0106 Resolved at `v1.4.1`

https://github.com/sue445/go-mod-tidy-pr/releases/tag/v1.4.1
